### ISSUE TITLE
Cannot find ExcelMerge.spec

### ISSUE THREAD

**Issue by LShining** [RoneBlog/ExcelMergeTool#1]
您在superpack.bat中写道
`set "spec_file=%cd%\ExcelMerge.spec"`
但是repo中并没有此文件，请问它是如何生成的？
另，我在执行这个批处理脚本的时候报错，请问有什么相关配置需要做？

**Comment by ThisIsRone** [comment]
刚刚更新了一个InstallDependent.py你得一下这个文件，运行一下。
报错的原因可能是因为没有pyinstaller库
pyinstaller是一个用于打exe的python库
在运行打包时，dist/用于存放exe或者其他的包   build/和 ExcelMerge.spec 是生成的临时文件
之所以写这个删除的逻辑，是因为之前有次删除临时文件时，把刚写的代码也删除了。
另外，有一个小的建议，如果有报错的话，可以说一下报错的内容，这样有助于快速定位

**Comment by LShining** [comment]
![image](https://user-images.githubusercontent.com/6957891/84615712-4de3fc80-aefc-11ea-8f4f-2aa575d42594.png)

其中superpack2是我将原文件另存为了ANSI格式。所有的依赖包我应该都安装了。

**Comment by LShining** [comment]
您好，我已经找出了问题所在，这个bat前面带有两个字节的UTF-8的BOM(Byte Order Mark)，导致脚本无法被Windows识别。直接复制所有内容并粘贴到新建的ANSI文本文件中并另存为，可以解决该问题。

**Comment by ThisIsRone** [comment]
厉害！👍
